import nontrigonometric_harmonic_analysis_involving_wavelets_foundation_canonical_lane_mathlib.GateLemmas
import nontrigonometric_harmonic_analysis_involving_wavelets_foundation_canonical_lane_mathlib.FinalTheorem
