import nontrigonometric_harmonic_analysis_involving_wavelets_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace nontrigonometric_harmonic_analysis_involving_wavelets_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end nontrigonometric_harmonic_analysis_involving_wavelets_foundation_canonical_lane_mathlib
end HautevilleHouse
